# .github/workflows/deploy.yml
name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # 你可以根据需要更改 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Archive dist folder
      run: tar -czf dist.tar.gz -C dist .

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Copy files via SCP
      env:
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_PORT: 22
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PASS: ${{ secrets.REMOTE_PASS }}
      run: |
        apt-get update && apt-get install -y sshpass
        sshpass -p "$REMOTE_PASS" scp -o StrictHostKeyChecking=no -P $REMOTE_PORT dist.tar.gz $REMOTE_USER@$REMOTE_HOST:/path/to/remote/directory
